### ISSUE TITLE
Question: does this actually upload an image to the server

### ISSUE THREAD

**Issue by ganySA** [pfafman/meteor-photo-up#1]
Hi

I am trying to understand if this physically actually will save an image on the server and if so where...

I am currently using meteor-file-collection gridfs and am looking for a means to edit images prior to saving. Is there a way to send data into something like file-collection? or is this only for physical uploads?

Thanks

**Comment by pfafman** [comment]
This package does not save the image to the server.  It only gets it into meteor on the client, via the callback.  You then save it were you want.

For example you could drop this into a form for a user preference where they can add an image and then on save on the form push that image into their profile if you wanted.
