### ISSUE TITLE
ReferenceError: event is not defined

### ISSUE THREAD

**Issue by kakajansh** [pfafman/meteor-photo-up#10]
on line [361](https://github.com/pfafman/meteor-photo-up/blob/master/lib/photoUp.coffee#L361)

```
  'click .crop': (e, tmpl) ->
    e.preventDefault()
    event.stopPropagation()
```

`event` should be `e`. Sorry, i am just beginner on github.. i think i need look up `pull requests` )

**Comment by pfafman** [comment]
Fixed.  Thanks for the head up.
