### ISSUE TITLE
Question: some default config settings

### ISSUE THREAD

**Issue by ganySA** [pfafman/meteor-photo-up#4]
Hi

i think your packages is great but i am struggling with understanding how the two packages (loadImages + crop) work with each other...

When i click the item to upload, it place an image inside the box however the image is already scaled down to the size of the box.... which is currently 200x200 ... I cant move the image around or do anything with it... what do i do from here... this is my loadImage config.

```
loadImage: 
            {
                aspectRatio: 1 / 1,
                maxWidth: 640,
                minWidth: 640,
                maxHeight: 640,
                minWidth:640,
            },
```

**Comment by pfafman** [comment]
jCrop settings are the ones that let you move resize etc.

This is why I did not want to push it to Atmosphere yet for I have not have time to bullet proof the docs and get my demo site up.

Just updated docs.
- crop - bool if true then do jCrop after upload.
- jCrop - { ... Jcrop options [see site](http://deepliquid.com/content/Jcrop_Manual.html#Setting_Options) ... }

**Comment by ganySA** [comment]
no problem - will wait and play around. i think this package is so needed right now and the fact it uses materializecss works 100% for me. the next best thing is the cropper package but i cannot seem to get it to do what i want either.

One point is that the load time of the intial image is a good few seconds 3-5 is this normal?

**Comment by ganySA** [comment]
Btw thank you for making this package.

**Comment by pfafman** [comment]
Since it is all on the client should be almost instantaneous.  It is in my meteor apps that use it.

**Comment by pfafman** [comment]
See
- https://github.com/pfafman/meteor-materialize-testsite
- http://pfafman.meteor.com
