### ISSUE TITLE
Question on performance

### ISSUE THREAD

**Issue by ganySA** [pfafman/meteor-photo-up#6]
Hi Tim

When i click on the load image into the image box, i have at least a 2-4 lag, i am no clue why this is the case... but it seems un-natural, almost as if the file is being uploaded or virus scanned or something bizarre. This happens in chrome and ie and i have tested it on your demo sites and i have the same problem - i assume it would be something to do with the Javascript image load library....

Any thoughts.

**Comment by pfafman** [comment]
I have tested on pfafman.meteor.com from both safari and chrome on OS X and IE on windows 7 and see no visible lag.  There is no real upload going on since all the code is on the client.  If you are having issues with some plugin virus checker I am not able to help you.

**Comment by ganySA** [comment]
@pfafman

I have done some more testing on this and your absolutely right. for some reason on my server machine this is the standard behaviour for some reason - on my mac its instantaneous.

I would ask one other question from you which i am trying to wrap my head around. I would like to save images at the highest possible resolution so when displayed across devices it will not blur.

My question is if i use this plugin and load a 600x600 image into the container, then crop a portion of it, will it in fact crop the larger of the images or will it simply crop the tiny image that i place in the container? I guess i would like to have the maximum size image in a small container for easy cropping...

**Comment by pfafman** [comment]
I believe it crops the full image.  But it will be up to how you set up the crop settings so this is a question for that repo.

**Comment by pfafman** [comment]
I am closing this.  If this is still some issue reopen.
