### ISSUE TITLE
Crop button disappears after resetting

### ISSUE THREAD

**Issue by kakajansh** [pfafman/meteor-photo-up#9]
1. Visiting http://pfafman.meteor.com/photoUpTest
2. Uploading an image
3. Select cropping area and click `Crop`
4. `Reset`ting
5. Uploading second image
6. Selecting cropping area  
   And there no `Crop` button.

**Comment by pfafman** [comment]
This is now fixed.  By moving the cropCords ReactiveVar from being attached to a template to a local variable not attached to a template it now works.  This seems to be some complicated issue with meteor's reactivity when the template is destroyed and then re-created.  Although this fixes the issue not sure I am happy with it.
